changelog:
  categories:
    - title: Breaking Changes
      labels:
        - breaking-change
    - title: Features
      labels:
        - feature
        - enhancement
    - title: Fix
      labels:
        - fix
    - title: Other Changes
      labels:
        - "*"
