name: Docker-build-n-push

on:
#  push:
#    tags: [ 'v*.*.*' ]
  release:
    types: [released, prereleased]

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm/v6
          - linux/arm/v7
          - linux/arm64
    permissions:
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3.3.0
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Lowercase repo name
        run: |
          echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: ${{ matrix.platforms }}
          tags: ${{ github.event.action == 'released' && format('ghcr.io/{0}:latest,', env.REPO) || '' }}ghcr.io/${{ env.REPO }}:latest-dev,ghcr.io/${{ env.REPO }}:${{ github.ref_name }}
          build-args: |
            BUILD_DATE=${{ github.event.repository.updated_at }}
            BUILD_REF=$(git rev-parse --short HEAD)
            BUILD_VERSION=${{ github.ref_name }}
